config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :index ]
  root :to => "posts#index"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/post', to: 'posts#new',     via: 'get'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_create :create_remember_token
  has_many :posts


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new

  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to root_path
  end

  def signed_in_user
    unless signed_in? 
    flash[:danger] = "Please sign in to post"
    redirect_to signin_path 
    end
  end

  def post_params
    params.require(:posts).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Welcome !'
      sign_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'email/password combination incorrect'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in user
    remember_token = User.new_remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    cookies.permanent[:remember_token] = remember_token
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_out
    remember_token = User.new_remember_token
    current_user.update_attribute(:remember_token, User.digest(remember_token))
    @current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class:"container">
      <%= link_to "Members Only", root_path, id: "logo" %>

      <ul class="nav navbar-nav navbar-right"> 
        
        <% if signed_in?%>
          <li><%= link_to "Post", post_path %></li>
          <li><%= link_to "Logout (#{current_user.name})", signout_path , method: "delete"%></li>
        <% else %>
          <li><%= link_to "Login", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </header>

  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>

  <footer class="footer">
     <small>
      Exercice for  <a href="http://www.theodinproject.com/ruby-on-rails/authentication">The Odin Project</a>.
      See code on <a href="https://github.com/AtActionPark/odin_members_only">Github</a>
    </small>
  </footer>
</body>
</html>

app/views/posts/index.html.erb
<div class="content">
<ul >
<% @posts.each do |p| %>
<% if signed_in? %>
    <div class="user">
      <%= User.find(p.user_id).name if User.exists?(p.user_id) %>
      said :
    </div>
    <% end %>

  <li class="postslist">
    <div class="post">
      <%= p.content %>
    </div>

    
  </li>
<% end %>
</ul>
</div>

app/views/posts/new.html.erb
<div class="center jumbotron">
  <h1>Post </h1>

  <%= form_for :posts, url: posts_path do |f| %>


  <%= f.text_field :content %>

  <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>

  <% end %>

</div>